name: Upload to S3
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set the timeout to 30 minutes (or any value you prefer)
    steps:
      - uses: actions/checkout@v2

      - name: Generate result file
        run: |
          sudo -E bash -x nmap-pentest.sh
        env:
          FCR: ${{ secrets.FCR }}
          DO_PRIME: ${{ secrets.DO_PRIME }}
          DO_HOME: ${{ secrets.DO_HOME }}
          HETZNER1: ${{ secrets.HETZNER1 }}
          HETZNER2: ${{ secrets.HETZNER2 }}
          HETZNER3: ${{ secrets.HETZNER3 }}
      
      - name: Upload ZIP to S3
        uses: NotCoffee418/s3-zip-upload@v1.4
        env:
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_REGION: us-east-1
          SOURCE_MODE: ZIP
          SOURCE_PATH: /home/nmap/result/
          DEST_FILE: nmap.zip
